services:
  api:
    build: .
    ports:
      - "8020:8020"
    volumes:
      - ./logs/log.log:/log.log
      - ./db/transcriptions.db:/transcriptions.db
    environment:
      - WHISPER_MODEL=openai/whisper-tiny
      - HF_TOKEN=<INPUT YOU HUGGINGFACE API TOKEN HERE>
      - HF_MAX_RETRIES=5
      - HF_RETRY_DELAY=2
      - VAD_THRESHOLD=0.3
    restart: unless-stopped